version: '3.8'

services:
  rag-app:
    image: r.deso.tech/dsml/cage:latest
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 60s
